### ISSUE TITLE
What about localization?

### ISSUE THREAD

**Issue by jaynakus** [secretyouth/react-datez#13]
Hello, is it using moment localization or you had implement static month names? We could not see months in another language even if we changed moment language.

**Comment by jchapelle** [comment]
Localization would be very appreciated ! Great job by the way ...

**Comment by jaynakus** [comment]
So I could wait and added localization support. Moreover I needed some better year button. Added ability to change that button with custom image or any node. Please merge and release new version.

**Comment by secretyouth** [comment]
@jaynakus Thanks! I'll have to look at this during the week. I am a bit busy with a major product release, but when I have some time ill review and get this released 👍

**Comment by secretyouth** [comment]
@jaynakus - added in new release 1.3.0

Enjoy :)
