### ISSUE TITLE
style problem

### ISSUE THREAD

**Issue by gvaldambrini** [secretyouth/react-datez#28]
First of all, thank you for your component.
I think the current version is distributed with a style problem, as the calendar appears like this:
![screen shot 2018-02-18 at 21 46 38](https://user-images.githubusercontent.com/2461921/36356658-3df787e0-14f5-11e8-85a4-fe5958079c6f.png)

After some investigations, I found that the demo server includes a [css box sizing rule](https://github.com/secretyouth/react-datez/blob/master/app/styles/components/base.css#L2) which is not in the `dist.css` file. Adding a rule in my css:
```
.rdatez * {
    box-sizing: border-box; 
}
```
fixes the issue.

**Comment by secretyouth** [comment]
Nice, I added it to the component to make sure no one else has this issue 😄 Will be in next release.
