### ISSUE TITLE
Allow start of week to be Sunday

### ISSUE THREAD

**Issue by uorji3** [secretyouth/react-datez#29]
It would be nice to have the flexibility to choose the start of week on Sunday or Monday.

**Comment by secretyouth** [comment]
Seems pretty straight forward. Ill look into this soon 😀

**Comment by vongdarakia** [comment]
I'd really like to see this feature out soon

**Comment by vongdarakia** [comment]
I just made a pull request for the feature here #44

**Comment by secretyouth** [comment]
Thanks @vongdarakia - Completed and ready for release today.
