### ISSUE TITLE
startDate prop is not having any effect

### ISSUE THREAD

**Issue by mandriv** [secretyouth/react-datez#32]
I am setting startDate as `moment().subtract(7, 'days').format()` but the dates before my `startDate` are still available to pick. I also tried using the format that I set in `dateFormat` prop but with no effect. 

Any feedback would be much appreciated.

**Comment by secretyouth** [comment]
@mandriv 

We don't have the functionality to disable dates from the startDate. I only created functionality for a date range (which disables outside of this range).

I suggest you pass through a startDate and endDate in the future (200 years) which would allow you to disable anything before a specific date.

`<Field name="exampleDate6" component={ReduxReactDatez} displayCalendars={2} startDate={moment().subtract(7, 'days').format()} endDate={moment().add(200, 'years').format()} />`

Hope this helps!

**Comment by JimmySorza** [comment]
thanks @secretyouth
