### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by bencoder** [secretyouth/react-datez#4]
Looks nice (came here from https://github.com/airbnb/react-dates/issues/25#issuecomment-309218584) but I might not be able to use it without an explicit licence

**Comment by anfedorov** [comment]
yeah, not sure who can use this without a license. Russia hackers? :-P

**Comment by secretyouth** [comment]
@anfedorov @bencoder - I was targeting hackers.

Thanks guys! It now has a LICENSE! 🍰
