### ISSUE TITLE
Dependencies express` version security warning

### ISSUE THREAD

**Issue by joemewes** [secretyouth/react-datez#43]
hi.

current `express` version is fixed at "4.14.1", which has a dep on `fresh` which has a `Regular Expression Denial of Service` security warning when running npm audit.  FYI.

```
 Package       │ fresh                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.5.2
```

is it possible to up the version of express or allow for ^minor updated versions of express/deps in package.json?

what's best?  

can create a PR is needed. and thanks for the project... it's great!

**Comment by secretyouth** [comment]
Thanks to @kladess who fixed this. Release coming soon.
