### ISSUE TITLE
Property "enableClearIcon" to clear selected date

### ISSUE THREAD

**Issue by emibadin** [secretyouth/react-datez#45]
It is strange that a component like this type does not have an event to clean the selected value

**Comment by secretyouth** [comment]
I get what you mean, if you accidentally select a date, you cannot unselect it.

What I can do, is clear the date on the calendar initialisation button.

**Comment by secretyouth** [comment]
I've added functionality where the input icon will change to a cross to allow a user to clear the field. On mobile the X (cross) will clear the input, selecting a date will close the overlay.

Due in next release 1.3.4
